# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=40)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('main_picture', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=400)),
                ('recalls_counter', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StallPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stalls.Stall')),
            ],
        ),
        migrations.AddField(
            model_name='foodlist',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stalls.Stall'),
        ),
    ]
